### ISSUE TITLE
Consider exposing shard details

### ISSUE THREAD

**Issue by ktoso** [akka/akka-management#14]
Information like where which shards are allocated etc could be pretty interesting to expose here.

**Comment by ktoso** [comment]
FYI @patriknw

**Comment by sebastianharko** [comment]
I'm willing to implement this if it's considered useful.

**Comment by patriknw** [comment]
that would be great, @sebastianharko 
Thanks

**Comment by sebastianharko** [comment]
@patriknw @ktoso So I'm going to get these shard details via ShardRegion.GetClusterShardingStats  and ShardRegion.ClusterShardingStats  etc... We do not want to have akka-cluster-management depend on the sharding JAR because akka-cluster-management should be lightweight. 

So, I'm going to do this using reflection. If the akka.cluster.sharding is not on the class path, we can return something like Bad Request via the HTTP API.  

Let me know if this approach is ok or if there's another approach that does not require reflection.

**Comment by patriknw** [comment]
Not sure it has to be lightweight. Doing all of it with reflection doesn't sound attractive. Perhaps you can have the dependency as `provided` and and detect at runtime if you can "load this module". Perhaps that is what you described?

**Comment by sebastianharko** [comment]
@patriknw yes you're right - I totally forgot about "% provided", that's definitely the right approach.

**Comment by vikasuy** [comment]
This would be really helpful. 
@patriknw what's the best way to find the shard regions actors -- will they need to be passed in explicitly to `ClusterHttpManagement`?

**Comment by patriknw** [comment]
I suggest the http GET request should contain the sharding `typeName` as part of the path. That `typeName` can then be used in `ClusterSharding(system).shardRegion(typeName)` to get the region `ActorRef`. That method will throw `IllegalArgumentException` if there is no such region, so catch that and treat as 404.

**Comment by vikasuy** [comment]
Thanks @patriknw. 
I've been looking into this. Building the route inside `ClusterHttpManagementRoutes` is not difficult, but testing the route is tricky. Do you have a suggestion for mocking out `ClusterSharding`. 

At a high level, i imagine this as code inside `ClusterHttpManagementRoutes` as follows:

```
private def routeGetShardInfo(cluster: Cluster, shardRegionName: String) = {
  val clusterSharding = ClusterSharding(cluster.system)
  // get shard region actor from clusterSharding and return a response
}
```

The problem is that since the route initializes `ClusterSharding`, the tests can't pass in a `mock(classOf[ClusterSharding])`, as they do in testing other routes. One option is to pass `ClusterSharding` as an argument to `apply` in `ClusterHTTPManagementRoutes`, but this won't work for users of akka cluster who don't use cluster sharding.

**Comment by vikasuy** [comment]
On second thought, if the user of `ClusterHTTPManagement` doesn't pass in `ClusterSharding` in `apply` themselves, then none of this will work because `ClusterSharding` is stateful. 

@patriknw is it worth leaving the sharding jar as `provided` at this point then?

**Comment by patriknw** [comment]
I don't know exactly how to structure this. Could it be a separate route? It should be possible to combine routes? Otherwise if that is too complicated we can just say that cluster sharding is a required dependency.

BTW, I don't think you "pass in" ClusterSharding. It's an extension, so by passing in the `system` you can get the `ClusterSharding` and it's region `ActorRef`.

For testing, I think you can test with a real single-node cluster, just join itself.

**Comment by vikasuy** [comment]
@patriknw what I meant was that `ClusterSharding.shardRegion(typeName: String)` looks in a local val for the shard region actors https://github.com/akka/akka/blob/8b5e01bcf7307ca5107cf36b4369dc6fea19686f/akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterSharding.scala#L389

So if user doesn't pass in the `ClusterSharding` instance they used to start their `ShardRegion` actors, and `ClusterHTTPManagementRoutes` initializes its own `ClusterSharding` off the `system`, then  `ClusterHTTPManagementRoutes`'s call to`shardRegion(typeName: String)` will never be able to load the shard regions from its local `regions` map. 

If we don't want to pass in `ClusterSharding`, then the alternative is to try to find the ShardRegion via ActorSelection. 

Do you have thoughts on which approach is better?

**Comment by patriknw** [comment]
`ClusterSharding` is an [Akka extension](http://doc.akka.io/docs/akka/2.5/scala/cluster-sharding.html) so there will only be one instance for a given `ActorSystem`. What you describe can only happen when running several actor systems in the same jvm and mixing them up with wrong `CusterHTTPManagementRoutes` (belonging to another actor system).
