### ISSUE TITLE
Why is it called SimpleServiceDiscovery ?

### ISSUE THREAD

**Issue by patriknw** [akka/akka-management#229]
Is there some other ServiceDiscovery?
Is there also an advanced or complicated ServiceDiscovery?

I'd suggest to just name it `ServiceDiscovery`, and if we ever want something more we can invent another name for that, such as `ExtendedServiceDiscovery`.

**Comment by ktoso** [comment]
AFAIR historical reasons to avoid conflicting with Lagom... (I picked the “simple”name).

In that respect it is “simple” because it does not do the things the lagom one did - the balancing aspects, which we aim to resolve using a different api nowadays.

With how things are heading now I do agree it should be renamed to just “ServiceDiscovery”

**Comment by patriknw** [comment]
I see that `ServiceDiscovery` is an extension. Should we have an extension there at all. There are needs for more than `ServiceDiscovery` implementation, e.g. one for ClusterBootrstrap and another for gRPC.

I think we should remove the extension and provide a factory method to create an instance from config.

**Comment by ktoso** [comment]
There’s two things. There is a “default one” and “give me a specific one” which (I think...) also exists already on the extension. 

The idea was to have one if people don’t care about which method is used but know it is cofiguted to the “right one” they would use the extension provided one. There would be able to use the extension in the same way we do ‘journalFor’ nowadays

**Comment by patriknw** [comment]
ok, then `loadServiceDiscovery` should become public (and perhaps moved from the object to the extension class).

**Comment by TimMoore** [comment]
I'm not sure whether "default one" makes much sense, because there are two entirely different use cases:

1. I want to discover the peer nodes of my own service
2. I want to communicate with other services

Until now, Akka Discovery is oriented around the first case, but this is the less-common case in that it is probably only useful for Cluster Bootstrap, whereas communication with other services will happen in a variety of different places, including other libraries and in user code.

If we want to retain the concept of a default implementation, it should be oriented for the second case, but then we would need a new mechanism to configure Cluster Bootstrap with a different one.

**Comment by ktoso** [comment]
> If we want to retain the concept of a default implementation, it should be oriented for the second case, but then we would need a new mechanism to configure Cluster Bootstrap with a different one.

Yes, I think that'd be good. The use case for the default one is when users would use it with some APIs that we don't control and they still want to get the discovery powers we provide them with. e.g. they use async-http-client but want to use discovery to figure out from some consul thing where to call and similar weird scenarios. I'd assume the default one we'd make the aggregate of config + dns then, and allow changing it by users.

**Comment by TimMoore** [comment]
Yes, sounds good. I was also missing the information that the `akka.management.cluster.bootstrap.discovery-method` property already exists.

https://github.com/akka/akka-management/blob/cde738a2f23da6078ff011783f0e31195287b630/cluster-bootstrap/src/main/resources/reference.conf#L36-L42

I suggest that we update Cluster Bootstrap docs to recommend setting that property and clarify the distinction.

**Comment by raboof** [comment]
The comment at https://github.com/akka/akka-management/blob/cde738a2f23da6078ff011783f0e31195287b630/discovery/src/main/scala/akka/discovery/SimpleServiceDiscovery.scala#L19 suggests it's 'simple' because it doesn't include monitoring for changes

**Comment by TimMoore** [comment]
In that case (and considering that we may never decide to implement monitoring for changes) I agree with @patriknw's initial suggestion of calling this `ServiceDiscovery` and calling the hypothetical event-driven version something more descriptive when and if it is created.

**Comment by raboof** [comment]
We do have a use case for listening for changes (people have been requesting the akka-http connection pool to take into account DNS TTL's and reresolve domain names as needed), but it'd still make sense to rename `SimpleServiceDiscovery` to `ServiceDiscovery` and figure out how to name/approach the refreshing case later.

**Comment by ktoso** [comment]
Another point of confusion was that the Akka extension is also called ServiceDiscovery hm...
Though yeah, renaming the Simple one away from that would be good..

**Comment by TimMoore** [comment]
If we're going to rename and break the existing API, it would be good to do it sooner, as we keep adding more code that depends on the current API! :smile:

**Comment by chbatey** [comment]
Renamed when moved to Akka
