### ISSUE TITLE
Docs reference snapshot version

### ISSUE THREAD

**Issue by johanandren** [akka/akka-management#255]
See here: https://developer.lightbend.com/docs/akka-management/current/bootstrap.html#dependencies 

A version like "0.17.0+20180718-1128" is listed because of something with the doc-deployment process.

**Comment by johanandren** [comment]
@raboof did you look into this and figure something out?

**Comment by patriknw** [comment]
It's working in Alpakka somehow. Don't know if it's related but Alpakka is using `addSbtPlugin("com.dwijnand" % "sbt-dynver" % "3.0.0+4-1be64920")`

**Comment by ktoso** [comment]
Thanks for the fix in tech-hub itself @2m!
Once we publish again it should be fine then

**Comment by 2m** [comment]
Since this is a Techhub change, we needed to clean cached documentation builds and then kick the publish process. I removed latest cached docs from:

https://bintray.com/typesafe/techhub-docs/akka-management-current
https://bintray.com/typesafe/techhub-docs/akka-management-0.17.0

And then triggered deployment:

https://github.com/lightbend/techhub#triggering-deployment-on-the-microsite-push

**Comment by 2m** [comment]
Docs have been republished:

https://developer.lightbend.com/docs/akka-management/current/
https://developer.lightbend.com/docs/akka-management/0.17.0/

**Comment by ktoso** [comment]
Awesome!

**Comment by patriknw** [comment]
Thanks so much, @2m
