### ISSUE TITLE
kubernetes-api discovery method: determine pod namespace automatically

### ISSUE THREAD

**Issue by adam-sandor** [akka/akka-management#345]
Version 0.18 can only work if the pods run in the default namespace. Revision 57312c4 improves this by looking at the NAMESPACE environment variable to determine the namespace.  This method still requires that the user sets the environment variable in Kubernetes. 
The fully automated way to discover the namespace is to look at the `/var/run/secrets/kubernetes.io/serviceaccount/namespace` file, which is always mounted into a pod and contains the current namespace.

**Comment by jroper** [comment]
Likewise, we may be able to be smarter with cluster bootstrap, auto detecting the label that needs to be selected, instead of needing to configure the `service-name` manually. Though it might be a bit harder, since the Kubernetes API lookup for the cluster bootstrap is unaware that it's looking up itself, it would have to plug in config for cluster bootstrap itself. Not sure.

**Comment by jroper** [comment]
Actually, if you're only using `kubernetes-api` for cluster bootstrap, and not general service discovery, then you can just hard code the selector.
