### ISSUE TITLE
Documentation and example for cluster formation with Istio

### ISSUE THREAD

**Issue by TimMoore** [akka/akka-management#352]
It's not totally straightforward to configure clustering/cluster bootstrap when running Kubernetes with Istio installed. There are some tips in #209. It would be nice to make this advice more visible, with a complete recipe at https://developer.lightbend.com/docs/akka-management/current/bootstrap/recipes.html

**Comment by raboof** [comment]
Perhaps (based on) https://github.com/jroper/akka-ddata-shopping-cart-knative?

**Comment by chbatey** [comment]
From my limited understanding of Itsio any of the tradeoffs for making it work with Akka Cluster are not suitable for production so should we really document one of them? Don't you have to remove health checks?

**Comment by TimMoore** [comment]
I think you're right, @chbatey that we don't have a solid solution yet (particularly given https://github.com/akka/akka-management/issues/209#issuecomment-476067278). Maybe we should explicitly recommend against using Istio until there is a better solution in place. IIUC the readiness probe would only have to be disabled for the service defining `management` and `akka-remote`, which could be separate from the one serving normal HTTP traffic.

**Comment by jroper** [comment]
Documentation was written in #568. Given that the only difference between an Istio deployed app and a regular Kubernetes app is two annotations, I'm not sure that a full example is warranted. We could update one of the existing examples to have the Istio annotations, since they are benign if present when Istio is not in use, with a comment saying "these are necessary when using Istio, if not using Istio, they can be deleted." Though that might add unnecessary noise to the spec for the general case.

**Comment by TimMoore** [comment]
I think the example in the documentation is sufficient for now. I'll close this issue now and work to get some customer feedback on the documentation. If we need to expand it, I'll raise new issues.

**Comment by TimMoore** [comment]
This documentation is now published at https://doc.akka.io/docs/akka-management/current/bootstrap/istio.html
