### ISSUE TITLE
Pluggable health check providers

### ISSUE THREAD

**Issue by jroper** [akka/akka-management#402]
Cluster membership is not the only aspect of a nodes health that a deployment platform should be checking. Generally, you also want to include checks for the health of other resources that you depend on for most of your operations, for example, databases, or other services that you're tightly coupled to and can't serve requests without. It should be possible to plugin in other providers of health information to the health check.

**Comment by jroper** [comment]
Btw, Kubernetes doesn't support multiple live/ready probes:

https://github.com/kubernetes/kubernetes/issues/37218

My suggestion is that the health check routes provider be moved into akka-management, and akka-management-cluster-http provide a health check probe that the routes provider picks up and uses.

**Comment by TimMoore** [comment]
The implementation in `reactive-lib` does support extension: https://github.com/lightbend/reactive-lib/blob/master/status/src/main/scala/com/lightbend/rp/status/ApplicationStatus.scala

The Akka Management checks could use a similar approach.

**Comment by patriknw** [comment]
Don't we already have a plugin mechanism for routes in Akka management and that can be used to add custom health check routes?

**Comment by chbatey** [comment]
I think there’s a use case for a single health check http endpoint that’s
made up of different health checks

**Comment by jroper** [comment]
@patriknw Kubernetes only supports one health check (or rather, one for live status, one for ready status). So the pluggable routes only allows an either or choice between using the cluster status, or your own for example database liveness check. We need pluggable checks to be served from a single route if we want the Kubernetes health check to be able to check more than just cluster status.

**Comment by longmuir** [comment]
It's not uncommon for companies to have conventions around the URLs used for health checks. It may be that a `/ready` and `/alive` on the Akka Management port are not the desired health check URLs.

As a simple solution, I'd suggest providing and documenting a programatic API for checking Akka Cluster's readiness (e.g. public boolean akkaClusterIsReady() {} or similar). Users can then create their own custom Health checks using the API of their preference (e.g. Play, Akka HTTP or Lagom) and simply call this method as part of their validation.

**Comment by renatocaval** [comment]
In addition to that, I think it will be useful to not include it automatically. Or at least, allow it to be added as an additional route directly in Lagom or Play. As implemented today, it's private and internal API [see here](https://github.com/akka/akka-management/pull/393/files#diff-b8ed4efd0c6e44f230a9ea6db349e4b9R21).

When integrating this with Lagom or Play, we will be starting another http server, the akka-mngt one, and is this server that we will be testing for readiness. 

It can be that the Play or Lagom server is in a deadlock or is mal-functioning and the readiness check, when added to a side akka-http server, won't detect it. 

Instead, we should be able to add the health check as an additional router in Play or Lagom server.

The route that we add to form the cluster can be separated from the main application.

**Comment by longmuir** [comment]
After using the Akka Management health checks in testing an application, I'm finding signalling readiness based purely on Akka Cluster states to not be that helpful. Much of the time the readiness probe is signalling `ready` when the app can't handle traffic yet. For example, the app is signalling ready, even though Akka Cluster Sharding has failed to initialize. There are too many other things that go into 'readiness' that go beyond Akka cluster formation, and much of them are around the application's context. Thus, I would much prefer to have a public Java/Scala API that I can call to validate cluster formation, as well as perhaps readiness of other components such as Cluster Sharding, Persistence, etc. This would allow me to develop a custom readiness check that is part the application's HTTP server, rather than Akka Management HTTP.

It may be a different issue, but having `WeaklyUp` default to "ready" also seems like a poor choice. As I recall from an earlier tests, with Akka Cluster Sharding or Cluster Singleton, `WeaklyUp` members will not be able to respond to requests.

**Comment by jroper** [comment]
@longmuir This is actually where having it served automatically by Akka I think is really helpful. Users shouldn't have to manually register a check for each Akka feature (clustering, cluster sharding, persistence providers, etc) that they're using - they might not even be aware of which are being used under the covers. A pluggable API would allow all of these features to automatically plug in their own readiness checks, allowing each feature to provide complete support for itself, instead of fragmented bits that a user has to know how to bring together with the correct health checks etc.

**Comment by longmuir** [comment]
@jroper Agree, that it would be a nice convenience to have readiness served by Akka such that it takes all of the different features into account. In that case, having the endpoint name configurable is important (e.g. /healthz). 

The above would be a nice convenience feature. I would still like the option to be able to call the readiness checks in your own code if you prefers to manage your own readiness/liveness checks.

**Comment by patriknw** [comment]
I have read up on the requirements and suggestions here. Would the following implementation work for everyone?

* Create a general purpose `HealthCheckRoutes` in `akka-management`, which by default is "empty" and returns `OK` for paths "/ready" and "/alive"
  * above paths should be configurable
* Make it possible to contribute real checks to the `HealthCheckRoutes` via configuration
  * e.g. the cluster member status checks are contributed from `akka-management-cluster-http` in that way and the current `ClusterHealthCheckRoutes` is removed
  * `HealthCheckRoutes` will combine all contributed checks into a result
  * it's mostly custom "ready" checks that will be added but let's support custom "alive" checks in the same way
  * to be able to contribute checks from a downstream library, e.g. cluster-sharding, we should not require a dependency to akka-management, i.e. the configured contributions should be of the shape `Function[ActorSystem, Future[Boolean]]`
  * should it be `Future[Boolean]` or just `Boolean`? I don't think there is any need for async checks since they will be retried?
  * we can support a few different shapes, e.g. `CompletionStage`
* Provide the cluster member status checks as a plain utility class

**Comment by TimMoore** [comment]
Kubernetes will log an event with the response body of failing probes, so it's useful for diagnostic purposes to include details in the response. It would be good to support aggregating a list of reasons from failing checks.

The most straightforward thing might be to make these checks `ActorSystem => Future[Done]`/`Function<ActorSystem, CompletionStage<Done>>`, using a failed `Future`/`CompletionStage` to specify the reason. Alternatively without an async check, it could be `ActorSystem => Try[Done]` for Scala and just `Function<ActorSystem, Done>` for Java, with the expectation that Java checks will throw an exception for failing checks (or even for both Java and Scala).

Otherwise, sounds good to me.

**Comment by patriknw** [comment]
Thanks for feedback, Tim.

Any opinions @jroper or @renatocaval before we start implementing this?

**Comment by chbatey** [comment]
Sounds good. I think async is useful for use cases where there isn't some state that is updated separately e.g. actively doing a database call to check the database is up when the health check is called rather than having another process updating a field the health check can read.

**Comment by chbatey** [comment]
@TimMoore @jroper and @renatocaval if you have time it would be great to get your feedback on PR #438

**Comment by chbatey** [comment]
Closed by #438

**Comment by renatocaval** [comment]
@chbatey, sorry, didn't get the time to review this. I trust it is good. ;-)
