### ISSUE TITLE
Kubernetes discovery docs use of namespaces

### ISSUE THREAD

**Issue by jroper** [akka/akka-management#408]
The [Kubernetes API cluster bootstrap docs](https://developer.lightbend.com/docs/akka-management/current/bootstrap/kubernetes-api.html) shows the use of a namespace called `akka-bootstrap`, which seems to imply that we're recommending that any Akka applications using the Kubernetes API discovery mechanism should be deployed into their own namespace.

This is not how Kubernetes namespaces are [meant to be used](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/). Namespaces exist to divide a cluster amoung different users with different resources quotas - eg, an organisation might have a namespace per team. For small deployments, they recommend just using the default namespace. Unless we expect that a typical organisation will have only one team that deploys Akka and only Akka apps, then we shouldn't be recommending the use of an `akka-bootstrap` namespace, our docs should just use the default namespace (or better, leave out the namespace and let it be all automatic).

**Comment by jroper** [comment]
That said, one reason why a specific namespace may have been used here is for security - if you grant read access to pods, you can see all that pods configuration, including passwords passed via environment variables. But I don't think namespaces are a good solution to that, since you would have to deploy one namespace per app to isolate them from each other, which is again very unidiomatic, and makes things confusing when locating services because you'll never just be able to look a service up by its name, you'll have to know its namespace too. The solution there is probably not to put secrets in the deployment config, but use Kubernetes secrets for everything.

This does make me feel that using the kubernetes-api is not the best way to achieve this, that dns would be a better approach - if only the service config necessary weren't so confusing.

**Comment by raboof** [comment]
I agree `akka-bootstrap` was a poorly chosen namespace example. OTOH, I don't think we want to promote deploying things to the default namespace, since for example on OpenShift AFAIK there typically is no such thing.

I agree DNS is an attractive bootstrap discovery mechanism for Kubernetes deployments now that we've added the TCP fallback (and further improvements are coming up), and perhaps we should promote this more actively. Could you describe in what way the service config necessary there is confusing (perhaps in another ticket)? Perhaps we can improve that.

As a concrete action for this ticket, I think it'd make sense to change the `akka-bootstrap` namespace name to something else, but keep out of the default namespace. `example-namespace`?

**Comment by chbatey** [comment]
We can remove the external service as it just adds noise to the DNS example. Only show the one that is required for bootstrap. I don't find it confusing that Akka Cluster formation requires a service to locate the other members.

**Comment by TimMoore** [comment]
Wouldn't that just result in a service that can form a cluster but can't be contacted from the outside? I don't think that's very realistic.

**Comment by raboof** [comment]
I think the specific action to take here would be to remove the `akka-bootstrap` namespace from the yaml resources, and make sure to switch to it (or a differently-named one) as the default namespace at the start of any scripts.

Perhaps we should move removing the external service to another issue?

**Comment by patriknw** [comment]
Look into if this should be part of 1.0

**Comment by raboof** [comment]
Moved not exposing the HTTP service in that test to issue #495
