### ISSUE TITLE
K8s-api: <pod-namespace> is not always replaced correctly

### ISSUE THREAD

**Issue by raboof** [akka/akka-management#424]
In https://travis-ci.org/akka/akka-management/jobs/470381438 we saw:

```
12/20 07:29:01 INFO [Appka-akka.actor.default-dispatcher-4] a.m.c.b.LowestAddressJoinDecider - Exceeded stable margins without locating seed-nodes, however this node [172.17.0.8:8558,172-17-0-8.<pod-namespace>.pod.cluster.local:8558] is NOT the lowest address out of the discovered endpoints in this deployment, thus NOT joining self. Expecting node [ResolvedTarget(172-17-0-6.akka-bootstrap.pod.cluster.local,Some(8558),Some(/172.17.0.6))] (out of [ResolvedTarget(172-17-0-6.akka-bootstrap.pod.cluster.local,Some(8558),Some(/172.17.0.6)), ResolvedTarget(172-17-0-8.akka-bootstrap.pod.cluster.local,Some(8558),Some(/172.17.0.8)), ResolvedTarget(172-17-0-7.akka-bootstrap.pod.cluster.local,Some(8558),Some(/172.17.0.7))]) to perform the self-join and initiate the cluster.
```

This suggests the placeholder value `<pod-namespace>` is not always correctly replaced. Related to #415

**Comment by jroper** [comment]
Here's the change that introduced the dependency: https://github.com/akka/akka-management/pull/238

**Comment by jroper** [comment]
So, here's the original issue that was trying to be solved: #236

The problem is, Kubernetes discovery uses hostnames, not IP addresses (this was done to make it compatible with Istio). But our self address is an IP address, which means we can't tell which of the contact points is ourselves when we try to match our IP address against the contact points. So #238 introduced a hack into cluster bootstrap that said if the configuration for Kubernetes is present, convert the IP address into a Kubernetes hostname. Now since #415 removed the namespace configuration in preference to reading it directly from the filesystem, the hack no longer works.

I think the best solution here would be to add a `selfAddress` method to Akka discovery, which defaults to returning the local hosts IP address, but can be overridden by Kubernetes to return the pods host name instead.

**Comment by jroper** [comment]
Of course, now that Akka discovery is part of Akka proper, getting this change in will take time, and we probably can't hold up a new release of Akka management until that's done. So, in the interim, we could introduce an optional trait into Akka management that bootstrap uses to discover the self address if the discovery method implements that trait, and have Kubernetes implement it.

**Comment by jroper** [comment]
Actually, I'm now not sure that the hack is needed anymore, due to #242, since matching both on hostname and on IP address are done. Though not sure how it works with Istio.
