### ISSUE TITLE
Suggested pattern on health check a typed actor

### ISSUE THREAD

**Issue by YikSanChan** [akka/akka-management#678]
akka version: 2.6.4

With FP-style typed actor, an actor is an object.

```scala
object DbActor {
  def apply() = ???
}
```

To hook the actor to akka-management health check probe, it seems ok to do:

```scala
object DbActor {
  final class ReadinessCheck extends (() => Future[Boolean]) {
    override def apply(): Future[Boolean] =
      ready.future
  }

  private val ready = Promise[Boolean]()

  // First, load data from DB
  // Second, ready.success(true) to pass readiness check
  def apply() = ???
}
```

and in application.conf:

```
akka.management {
  health-checks {
    readiness-checks {
      db-actor-ready = "com.example.example.DbActor$ReadinessCheck"
    }
  }
}
```

I steal the above pattern from https://github.com/hseeberger/akkounts/blob/master/src/main/scala/rocks/heikoseeberger/akkounts/HttpServer.scala#L38 which works fine for that case since there will only be 1 instance of HttpServer. Thanks @hseeberger 

However, in Akka world, it is possible that an actor has multiple instances by doing `context.spawn` multiple times, in which case I don't know how to health check different instances of the same "actor"/"behavior" correctly.

Any suggestion? Any alternative approach to do health check on FP-style typed actor? Thanks.

**Comment by johanandren** [comment]
Moved this to the Akka Management issue tracker since it is about that.

As @hseeberger says it is may not be possible to provide a general solution for this, however we could definitely add some recommendations/scenarios to the docs to guide users the right way.

Having one actor per system that watches the lifecycle of other actors coming and going and querying that from the healthcheck could be suitable in some cases, having a single watch actor that can be accessed from the health check can be achieved through an Akka extension.

Another option couldd be resource owner actors/logic could publishing events to the system event bus, which is local, and have a stateful healthchecker subscribe to the event bus for htose on system start.

The actors that come and go could also register themselves to some actor, to make it possible to query actors all that exist at a given point in time.

**Comment by YikSanChan** [comment]
@johanandren Thanks.

Having one-actor-per-system that monitors the health status of other actors is similar to the approach we're currently taking.

The event bus solution sounds reasonable too.

We gonna take a closer look after we're on k8s. Will either reopen this ticket or create a new one with much more details when it's time.
