### ISSUE TITLE
needs update to Akka 2.6.10

### ISSUE THREAD

**Issue by SethTisue** [akka/akka-management#783]
in the Scala community build at https://github.com/scala/community-build/pull/1252, I found that with Akka 2.6.10 there are compile errors:

```
[error] /Users/tisue/akka-management/cluster-http/src/test/scala/akka/cluster/http/management/scaladsl/ClusterHttpManagementRoutesSpec.scala:59:30: not enough arguments for constructor Member: (uniqueAddress: akka.cluster.UniqueAddress, upNumber: Int, status: akka.cluster.MemberStatus, roles: Set[String], appVersion: akka.util.Version)akka.cluster.Member.
[error] Unspecified value parameter appVersion.
[error]         val clusterMember1 = new Member(uniqueAddress1, 1, Up, Set(s"dc-$dcName"))
[error]                              ^
...
```

fyi @patriknw — it's always best if we can keep the community build on latest Akka

**Comment by raboof** [comment]
This test is using a private `Member` constructor that indeed changed between 2.6.9 and 2.6.10.

We don't normally upgrade the Akka version in 'sattelite' projects unless there's a reason to (since users can update anyway because of binary compatibility).

Upgrading in this case would mean upgrading from 2.5.31 to 2.6.10 - quite a jump, but perhaps it's a good opportunity since 2.5 goes out of official support November 6th anyway?

**Comment by chbatey** [comment]
And then do https://github.com/akka/akka-management/issues/830

**Comment by raboof** [comment]
master is on 2.6.10 since 76d37a2c
